import { supabase } from './supabase'

// ─── Shared select for circle members with profile info ───────────────────────
const MEMBER_SELECT = `
  role, joined_at,
  profiles!circle_members_user_id_fkey ( id, display_name )
`

// ─── Shape raw member row → clean member object ───────────────────────────────
export function shapeMember(row) {
  return {
    user_id:      row.profiles?.id,
    display_name: row.profiles?.display_name || 'Someone',
    initials:     (row.profiles?.display_name || 'S').slice(0, 1).toUpperCase(),
    role:         row.role,
    joined_at:    row.joined_at,
  }
}

// ─── Fetch all circles for a user ─────────────────────────────────────────────
export async function fetchCircles(userId) {
  const { data, error } = await supabase
    .from('circle_members')
    .select(`
      role,
      circles (
        id, name, description, is_personal,
        open_invites, created_by, created_at
      )
    `)
    .eq('user_id', userId)

  if (error) throw error

  const all = data.map(row => ({ ...row.circles, role: row.role }))
  return {
    personalCircle: all.find(c => c.is_personal) ?? null,
    circles:        all.filter(c => !c.is_personal),
  }
}

// ─── Fetch members of a circle ────────────────────────────────────────────────
export async function fetchCircleMembers(circleId) {
  const { data, error } = await supabase
    .from('circle_members')
    .select(MEMBER_SELECT)
    .eq('circle_id', circleId)
    .order('joined_at', { ascending: true })

  if (error) throw error
  return data.map(shapeMember)
}

// ─── Create a circle ──────────────────────────────────────────────────────────
// Trigger handle_new_circle() auto-adds creator as moderator
export async function createCircle(circleData, userId) {
  const { data, error } = await supabase
    .from('circles')
    .insert({
      name:         circleData.name.trim(),
      description:  circleData.description?.trim() || null,
      open_invites: circleData.open_invites ?? false,
      created_by:   userId,
      is_personal:  false,
    })
    .select()
    .single()

  if (error) throw error
  return { ...data, role: 'moderator' }
}

// ─── Update a circle (mod only — enforced by RLS) ─────────────────────────────
export async function updateCircle(circleId, circleData) {
  const { data, error } = await supabase
    .from('circles')
    .update({
      name:         circleData.name?.trim(),
      description:  circleData.description?.trim() || null,
      open_invites: circleData.open_invites,
    })
    .eq('id', circleId)
    .select()
    .single()

  if (error) throw error
  return data
}

// ─── Delete a circle (mod only — enforced by RLS) ─────────────────────────────
export async function deleteCircle(circleId) {
  const { error } = await supabase
    .from('circles')
    .delete()
    .eq('id', circleId)

  if (error) throw error
}

// ─── Promote a member to moderator ───────────────────────────────────────────
export async function promoteMember(circleId, userId) {
  const { error } = await supabase
    .from('circle_members')
    .update({ role: 'moderator' })
    .eq('circle_id', circleId)
    .eq('user_id', userId)

  if (error) throw error
}

// ─── Remove a member (mod only — enforced by RLS) ────────────────────────────
export async function removeMember(circleId, userId) {
  const { error } = await supabase
    .from('circle_members')
    .delete()
    .eq('circle_id', circleId)
    .eq('user_id', userId)

  if (error) throw error
}

// ─── Leave a circle (self) ────────────────────────────────────────────────────
export async function leaveCircle(circleId, userId) {
  const { error } = await supabase
    .from('circle_members')
    .delete()
    .eq('circle_id', circleId)
    .eq('user_id', userId)

  if (error) throw error
}

// ─── Generate an invite code ──────────────────────────────────────────────────
// code is auto-generated by DB default, we just insert and read it back
export async function generateInviteCode(circleId, userId) {
  const { data, error } = await supabase
    .from('circle_invites')
    .insert({
      circle_id:  circleId,
      invited_by: userId,
    })
    .select('code')
    .single()

  if (error) throw error
  return data.code
}

// ─── Fetch existing active invite codes for a circle ─────────────────────────
export async function fetchInviteCodes(circleId) {
  const { data, error } = await supabase
    .from('circle_invites')
    .select('id, code, created_at, used_by, used_at, expires_at')
    .eq('circle_id', circleId)
    .is('used_by', null)   // only unused codes
    .order('created_at', { ascending: false })

  if (error) throw error
  return data
}

// ─── Join a circle by invite code ────────────────────────────────────────────
export async function joinByCode(code, userId) {
  // 1. Look up the invite
  const { data: invite, error: inviteErr } = await supabase
    .from('circle_invites')
    .select('id, circle_id, used_by, expires_at, circles(name)')
    .eq('code', code.toUpperCase())
    .single()

  if (inviteErr) throw new Error('Invite code not found.')
  if (invite.used_by) throw new Error('This invite has already been used.')
  if (invite.expires_at && new Date(invite.expires_at) < new Date()) {
    throw new Error('This invite has expired.')
  }

  // 2. Add user as member
  const { error: memberErr } = await supabase
    .from('circle_members')
    .insert({ circle_id: invite.circle_id, user_id: userId, role: 'member' })

  if (memberErr) {
    if (memberErr.code === '23505') throw new Error("You're already in this circle!")
    throw memberErr
  }

  // 3. Mark invite as used
  await supabase
    .from('circle_invites')
    .update({ used_by: userId, used_at: new Date().toISOString() })
    .eq('id', invite.id)

  return invite.circles
}